# Generated by Django 3.2.13 on 2022-05-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='이메일')),
                ('loginPW', models.CharField(max_length=200, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('nickname', models.CharField(max_length=200, verbose_name='닉네임')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('cellphoneNo', models.CharField(max_length=30, verbose_name='연락처')),
                ('createDay', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
            ],
            options={
                'verbose_name': '회원가입',
                'verbose_name_plural': '회원가입',
                'db_table': 'user',
            },
        ),
    ]
